---
- name: Provision the infrastructure
  hosts: localhost
  connection: local
  roles:
  - eduroam-provision


- name: Create the eduroam-hosts group
  hosts: eduroam-host
  connection: docker
  roles:
  - eduroam-configure


#- name: Provision the hosts
#  hosts: eduroam-hosts
#  roles:
#  - eduroam-configure
