---
# tasks file for roles/bootcamp
- name: Create the container
  docker_container:
   name: eduroam-host
   image:  "{{ eduroam_image }}"

- name: Create the eduroam-hosts group
  add_host:
   name: eduroam-host
   groups: eduroam-hosts

- name: debug the groups
  debug:
   var: "{{ item }}"
  with_items:
   - group_names

- name: Add the new container to the group

